# Generated by Django 2.0.4 on 2018-09-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=20, unique=True)),
                ('brandicon', models.ImageField(upload_to='brandicon')),
                ('brandurl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('showtype', models.CharField(choices=[('L', 'List'), ('T', 'Thumbnail'), ('B', 'Blend')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('page_imgUrl', models.ImageField(upload_to='page_img')),
                ('page_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('list_icon', models.ImageField(blank=True, null=True, upload_to='list_icon')),
                ('thumbnail_img', models.ImageField(blank=True, null=True, upload_to='thumbnail_img')),
                ('blend_avatar', models.ImageField(blank=True, null=True, upload_to='blend_avatar')),
                ('blend_desc', models.TextField(blank=True, null=True)),
                ('belongtocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Categorys', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('product_img', models.ImageField(upload_to='products_img')),
                ('clickUrl', models.URLField(blank=True, null=True)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('belongtocategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ProductCategorys')),
            ],
        ),
    ]
