# Generated by Django 2.0.4 on 2018-09-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180929_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='imgUrl',
            field=models.ImageField(upload_to='categorysimg'),
        ),
    ]
