# Generated by Django 2.0.4 on 2018-09-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180929_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_desc1',
            field=models.TextField(default='product desc 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_desc2',
            field=models.TextField(blank=True, default='product desc 2', null=True),
        ),
    ]
