# Generated by Django 2.0.4 on 2018-10-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20180929_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_desc1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_desc2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
