# Generated by Django 2.0.4 on 2018-10-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20181010_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorys',
            name='belongtocate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Categorys', to_field='name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='belongtocategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ProductCategorys'),
        ),
    ]
