# Generated by Django 2.0.4 on 2018-10-11 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20181011_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='belongtocategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.ProductCategorys', to_field='name'),
        ),
    ]
